/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  SpotcheckApiConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   suggestionBeanApi/v1
// Description:
//   This is an API

#import "SpotcheckApiConstants.h"

// Authorization scope
// NSString * const kGTLAuthScopeSuggestionBeanApiUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
